### ISSUE TITLE
custom authのlambdaがruntime errorをおこすようになった。

### ISSUE THREAD

**Issue by reibomaru** [team-azb/knowtfolio#115]
突然ウォレットログインが失敗するようになった。
[こんなログ](https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fverify_auth_challenge_response/log-events/2022$252F10$252F14$252F$255B$2524LATEST$255Db5bb03b84f7f404bb3358d4016a0b3fb)が出る  
[これ](https://ja.stackoverflow.com/questions/70105/cloud9-web3-py-%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E5%BE%8C%E5%AE%9F%E8%A1%8C%E6%99%82%E3%81%ABglibc%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E5%87%BA%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F)に似た状況。ビルドの環境とlambdaの実行環境が違うのが原因かも？

**Comment by reibomaru** [comment]
https://github.com/aws/aws-lambda-go/issues/340 
に従って、`CGO_ENABLED=0`のビルドオプションでビルドしたら動くようになったけど、よくわからん。。

**Comment by reibomaru** [comment]
[ドキュメント](https://pkg.go.dev/cmd/cgo#:~:text=The%20cgo%20tool%20is%20enabled%20by%20default%20for%20native%20builds%20on%20systems%20where%20it%20is%20expected%20to%20work.%20It%20is%20disabled%20by%20default%20when%20cross%2Dcompiling.%20You%20can%20control%20this%20by%20setting%20the%20CGO_ENABLED%20environment%20variable%20when%20running%20the%20go%20tool%3A%20set%20it%20to%201%20to%20enable%20the%20use%20of%20cgo%2C%20and%20to%200%20to%20disable%20it.)によるとクロスコンパイルのときは`CGO_ENABLED=0`になってくれるらしい。一方で、同じアーキテクチャでのコンパイルだと`CGO_ENABLED=1`になるらしい。

**Comment by reibomaru** [comment]
linux(alpine)のdockerを使っても同じ状態になる。また、dockerfileで`g++`が入っていない場合だと以下のエラーが起きる。
```
╷
│ Error: local-exec provisioner error
│ 
│   with null_resource.build_go_auth_challenge_functions,
│   on lambda.tf line 169, in resource "null_resource" "build_go_auth_challenge_functions":
│  169:   provisioner "local-exec" {
│ 
│ Error running command 'go build ./cmd/verify': exit status 2. Output: go: downloading github.com/ethereum/go-ethereum v1.10.23
│ go: downloading golang.org/x/crypto v0.0.0-20210921155107-089bfa567519
│ # github.com/ethereum/go-ethereum/crypto/secp256k1
│ cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
│ 
╵
make: *** [Makefile:97: apply-tf] Error 1
```
dockerfileで`g++`をいれてコンパイルを通したとしても[これ](https://github.com/team-azb/knowtfolio/issues/115#issue-1397196945)これと同じ状態で、lambdaが正常に動作しなくなる。

**Comment by shugo256** [comment]
#116 で解決済み
