### ISSUE TITLE
フロントでsignupフォームの値のバリデーションを実装する

### ISSUE THREAD

**Issue by reibomaru** [team-azb/knowtfolio#120]
- 電話番号
  - 電話番号のフォーマット
  - 重複チェック(エンドポイント必要かも)
- 名前
  - 文字列の長さ
  - 重複チェック(エンドポイント必要かも)
- パスワード
  - パスワードポリシーに当てはまっているかチェック

**Comment by shugo256** [comment]
#144 で同じことを言っているのでclose
