### ISSUE TITLE
walletAddressからuserIdを参照できるようにする

### ISSUE THREAD

**Issue by reibomaru** [team-azb/knowtfolio#153]
現状の問題
1. walletAddress重複問題
   - 複数のアカウントで同一のwalletAddressが登録される場合があり、１つの記事を複数のアカウントで編集することが可能になってしまう
   - これを防ぐにはwalletAddressについてユニークの制約を実装する必要がある
   - このためには、walletAddressからuserIdを検索する機能が必要になる
2. walletAddressでユーザー検索ができない
   - https://opensea.io/0xcdBDAFdFF0b863512863aA147903a9BC70c19513 みたいなイメージ
   - OpenSeaではアドレスとユーザーIdのどちらでも検索ができる
4. walletAddressでNFT化されていない記事の検索ができない(NFT化されていれば一応可能)

作業手順：

- [x] #157
- [ ] #158
- [x] #196
- [x] #159
- [ ] #160

**Comment by shugo256** [comment]
Cognitoでは、walletAddress -> userIdの検索ができない（カスタム属性は検索不可）なので、walletAddressとuserIdのマッピングはCognitoの外でやらざるを得ない

解決策の候補：
* Contract上で管理
  * 大事な対応関係をちゃんとオンチェーンにすると安心？（過激派）
  * 登録もContractの関数でやれば、SignUp時の署名がいらない（metamaskのUIが勝手に発動する）
  * 逆引きするには双方向のmappingが必要
  * 登録のたびにガス代がかかる
* DynamoDB上で管理
  * ガス代かからない
  * terraformいじるのが面倒

**Comment by shugo256** [comment]
=> 登録のたびにガス代がかかるのは、大多数と見られる「metamask持ってるけどお金払いたくない」ユーザに対して厳しいので、DynamoDBで行きます

**Comment by shugo256** [comment]
手順：

- [ ] ほげ
