### ISSUE TITLE
ClientでのwalletAddress参照箇所をCognitoからDynamoDBに修正

### ISSUE THREAD

**Issue by shugo256** [team-azb/knowtfolio#158]

**Comment by shugo256** [comment]
認証ずみuserにdynamodbのGetItem権限を与える必要がある
自分のidに一致するpartition key (=user_id)のみGetItemできるようにすると、後々wallet_addressを隠す機能が欲しくなった時にいいかもしれない
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/specifying-conditions.html#FGAC_DDB.OverviewUseCase:~:text=ID.%20This%20ID%2C-,%24%7Bwww.amazon.com%3Auser_id%7D,-%2C%20is%20a%20substitution

**Comment by reibomaru** [comment]
いくつか気づいたことが出てきた
- `post_confirmation`はサインアップとは異なるリクエストで発火する関数なので、`pre_sign_up`と`Metadata`を共有することはできない
- なので、cognitoから`wallet_address`属性を排除するのであれば、`pre_sign_up`でwallet_addressの検証をするのはあまり意味がない。なぜなら、`post_confirmation`でdynamodbへの登録をするので、そもそも`wallet_address`をcognitoのサインアップの際には必要ないため
- むしろ、`post_comfirmation`を発火させるときのリクエスト（これは、SMSで送信された認証コードをcognitoに送るリクエスト）のときに、`wallet_address`と`signature`をMetadataに入れる必要が出てきた。
- ただ、認証コードを送るときに`wallet_address`や`signature`を送信するのはUIとして少し不自然。とくに、認証コードを後から送信する場合に、署名をする必要があるが、ユーザーにとって分かりづらくなりそう。

**Comment by reibomaru** [comment]
結果的に、サインアップのときには`wallet_address`を登録せずに、サインアップしたらwallet登録画面に自動で遷移させれば良いのではないかと思い始めてきた
