### ISSUE TITLE
`validate_signup_form`でuser_idのバリデーションを入れる

### ISSUE THREAD

**Issue by shugo256** [team-azb/knowtfolio#234]
user id に絵文字を設定しようとしたら、cognitoのエラーが出たので、何らかの決まりがありそう
![image](https://user-images.githubusercontent.com/35961216/215474395-1cda2ec9-c855-4e98-a153-e835693cb801.png)

```
{"__type":"InvalidParameterException","message":"1 validation error detected: Value at 'username' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+"}
```

**Comment by shugo256** [comment]
ついでに`api`などの禁止ワードも入れることで、`/users/:id`ではなく`/:id`でアクセスできるようにすれば良さそう

**Comment by reibomaru** [comment]
https://github.com/team-azb/route-bucket-backend/tree/master/api/resources

**Comment by shugo256** [comment]
バリデーションはlambdaでやるので、禁止ワードはテキストファイルよりssm param storeで管理した方が扱いやすそう

**Comment by shugo256** [comment]
スラッシュも禁止で
